version: "3.8"

services:
  policycraft:
    image: policycraft:dev
    ports:
      - 8080:8080
    build:
      context: .
      dockerfile: ./Dockerfile.dev
      args:
        GO_VERSION: $GO_VERSION
        GOLANGCI_LINT_VERSION: $GOLANGCI_LINT_VERSION
    environment:
      POLICY_CRAFT_POSTGRES_URL: postgres://postgres:postgres@postgres:5432/policycraft?sslmode=disable
    # create a volume pointing to the source code to enable hot-reloading inside the container
    volumes:
      - .:/app/src
    command: go run ./cmd/policycraft
  postgres:
    image: postgres:14
    environment:
      POSTGRES_PASSWORD: postgres
      POSTGRES_USER: postgres
      POSTGRES_DB: policycraft
    volumes:
      - db:/var/lib/postgresql/data
    restart: unless-stopped
    ports:
      - 5432:5432
    healthcheck:
      test: pg_isready -U postgres
      interval: 2s
      timeout: 3s
      retries: 5
volumes:
  db:
