ARG GO_VERSION

FROM docker.io/golang:${GO_VERSION}-bullseye

# Install necessary packages
RUN apt-get update && \
    apt-get install -y git

ARG GOLANGCI_LINT_VERSION

RUN go install github.com/golangci/golangci-lint/cmd/golangci-lint@${GOLANGCI_LINT_VERSION}

RUN git config --global --add safe.directory /app/src

WORKDIR /app/src

COPY go.mod go.sum ./
RUN go mod download

COPY . .
