version: "3.9"

services:
  policycraft:
    image: policy-craft:dev
    build:
      context: .
      dockerfile: ./Dockerfile.dev
      args:
        PYTHON_VERSION: ${PYTHON_VERSION}
        POETRY_VERSION: ${POETRY_VERSION}
    environment:
      # to use postgres and asyncpg, we need to set it up the url driver as well: postgresql+asyncpg
      POLICYCRAFT_POSTGRES_URL: postgresql+asyncpg://postgres:postgres@postgres:5432/policycraft
    volumes:
      - .:/backend
    ports:
      - 8000:8000
    depends_on:
      postgres:
        condition: service_healthy
    command: poetry run uvicorn main:app --reload --host 0.0.0.0 --port 8000 --reload
  postgres:
    image: postgres:14
    environment:
      POSTGRES_PASSWORD: postgres
      POSTGRES_USER: postgres
      POSTGRES_DB: policycraft
    volumes:
      - db:/var/lib/postgresql/data
    restart: unless-stopped
    ports:
      - 5432:5432
    healthcheck:
      test: pg_isready -U postgres
      interval: 2s
      timeout: 3s
      retries: 5
volumes:
  db:
