name: ci-policy-craft-frontend

on:
  push:
    paths:
      - 'frontend/**'
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Use Node.js
        uses: actions/setup-node@v2
        with:
          node-version: '21.x'

      - name: Install dependencies
        run: make install

      - name: build
        run: make build

      - name: lint
        run: make lint
